on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" 
name: Multi Arch Build

jobs:
  push:
    name: docker build and push images
    runs-on: ubuntu-18.04 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1        
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64, linux/arm, linux/amd64
          push: true
          tags: leonnicolas/wg-tools:latest

